/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrgtutPkage;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishaan
 */
public class Lesson1 extends javax.swing.JFrame {

    /**
     * Creates new form Lesson1
     */
    public Lesson1() {
        initComponents();
        pnlLessson1.setPreferredSize(new Dimension(880, 800));
        setSize(new Dimension(1000, 1000));
        
        /*scrpnlLesson1.setPreferredSize(new Dimension(880, 800));
        setSize(new Dimension(1000, 1000));
       */ 
        /*
        btnBack.setBackground(Color.BLACK);
        btnBack.setOpaque(true);
        */
        JOptionPane.showMessageDialog(null, "Answer all the questions correctly\nto successfully complete Lesson 1", "Lesson 1:Quiz", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLessson1 = new javax.swing.JPanel();
        cmbQ1 = new javax.swing.JComboBox<>();
        cmbQ2 = new javax.swing.JComboBox<>();
        cmbQ3 = new javax.swing.JComboBox<>();
        cmbQ4 = new javax.swing.JComboBox<>();
        cmbQ5 = new javax.swing.JComboBox<>();
        cmbQ6 = new javax.swing.JComboBox<>();
        cmbQ7 = new javax.swing.JComboBox<>();
        cmbQ8 = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblback = new javax.swing.JLabel();
        lblQuestions = new javax.swing.JLabel();
        scrpnlLesson1 = new javax.swing.JScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlLessson1.setLayout(null);

        cmbQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ1);
        cmbQ1.setBounds(370, 70, 100, 20);

        cmbQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ2);
        cmbQ2.setBounds(370, 160, 93, 20);

        cmbQ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "dd" }));
        pnlLessson1.add(cmbQ3);
        cmbQ3.setBounds(560, 250, 93, 20);

        cmbQ4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ4);
        cmbQ4.setBounds(560, 330, 93, 20);

        cmbQ5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ5);
        cmbQ5.setBounds(310, 410, 93, 20);

        cmbQ6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ6);
        cmbQ6.setBounds(600, 490, 93, 20);

        cmbQ7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ7);
        cmbQ7.setBounds(350, 580, 93, 20);

        cmbQ8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Answer", "a", "b", "c", "d" }));
        pnlLessson1.add(cmbQ8);
        cmbQ8.setBounds(500, 660, 93, 20);

        btnSubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\submit35.png")); // NOI18N
        btnSubmit.setToolTipText("Submit for Evaluation");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlLessson1.add(btnSubmit);
        btnSubmit.setBounds(370, 700, 140, 40);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\arrow-112-32.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLessson1.add(btnBack);
        btnBack.setBounds(0, 0, 60, 50);

        lblback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\lesson1-40.png")); // NOI18N
        lblback.setText("jLabel1");
        pnlLessson1.add(lblback);
        lblback.setBounds(300, 10, 190, 40);

        lblQuestions.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\Lessons\\Lesson1Q.png")); // NOI18N
        lblQuestions.setText("jLabel1");
        pnlLessson1.add(lblQuestions);
        lblQuestions.setBounds(0, 0, 870, 770);
        pnlLessson1.add(scrpnlLesson1);
        scrpnlLesson1.setBounds(0, 0, 880, 760);
        pnlLessson1.add(filler1);
        filler1.setBounds(0, 190, 880, 230);

        getContentPane().add(pnlLessson1);
        pnlLessson1.setBounds(0, 0, 700, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Variables
    
    String lessonNum="Lesson 1"; //Current lesson number
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Previous Page
        //Tell user that no progress will be saved
        new LessonsScreen().setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Evaluation of the answers selected
        /*
        I can do this by checking each answer to see if each one is correct,and give the user feedback on which
        answers are incorrect in the form of a JOptionPayne output
        
        
        When all answers are correct,it should say congradulations and save this info in the textfile next to
        the users name,so that we can track their lesson progress.
        
        Will give their score as a fraction out of number of qustions they have to answer.
        
        Maybe have some type of variable that is parsed to the game menu screen giving this info 
        about the users progress and then setting this to the JTextfield.
        */
        
        Lesson obj=new Lesson();
        
        if (obj.evalAnswers()==true) {
            
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lesson1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lesson1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lesson1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lesson1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lesson1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbQ1;
    private javax.swing.JComboBox<String> cmbQ2;
    private javax.swing.JComboBox<String> cmbQ3;
    private javax.swing.JComboBox<String> cmbQ4;
    private javax.swing.JComboBox<String> cmbQ5;
    private javax.swing.JComboBox<String> cmbQ6;
    private javax.swing.JComboBox<String> cmbQ7;
    private javax.swing.JComboBox<String> cmbQ8;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel lblQuestions;
    private javax.swing.JLabel lblback;
    private javax.swing.JPanel pnlLessson1;
    private javax.swing.JScrollPane scrpnlLesson1;
    // End of variables declaration//GEN-END:variables
}
