/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrgtutPkage;

import java.awt.Dimension;

/**
 *
 * @author Ishaan
 */
public class LessonsScreen extends javax.swing.JFrame {

    /**
     * Creates new form LessonsScreen
     */
    public LessonsScreen() {
        initComponents();
        pnlLessons.setPreferredSize(new Dimension(500, 500));
        setSize(new Dimension(600, 380));
        
        //Read lesson progress for user from User class (Use the getLessonProgress method)
    }

    
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLessons = new javax.swing.JLabel();
        lblLessonNumber = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnLesson2 = new javax.swing.JButton();
        lblLessonProgress = new javax.swing.JLabel();
        lblLesson1Stats = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlLessons = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblLessons.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\LessonsMed.png")); // NOI18N
        lblLessons.setText("jLabel1");
        getContentPane().add(lblLessons);
        lblLessons.setBounds(210, 10, 190, 40);

        lblLessonNumber.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\lessonNum37.png")); // NOI18N
        lblLessonNumber.setText("jLabel2");
        getContentPane().add(lblLessonNumber);
        lblLessonNumber.setBounds(40, 70, 250, 67);

        btnPrevious.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\arrow-112-32.png")); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious);
        btnPrevious.setBounds(0, 0, 60, 50);

        btnLesson2.setText("Lesson 1");
        btnLesson2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLesson2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLesson2);
        btnLesson2.setBounds(60, 160, 200, 30);

        lblLessonProgress.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\progress37.png")); // NOI18N
        lblLessonProgress.setText("jLabel2");
        getContentPane().add(lblLessonProgress);
        lblLessonProgress.setBounds(340, 70, 180, 74);

        lblLesson1Stats.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblLesson1Stats.setForeground(new java.awt.Color(102, 255, 51));
        lblLesson1Stats.setText("5/7");
        getContentPane().add(lblLesson1Stats);
        lblLesson1Stats.setBounds(410, 160, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\Images\\background.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 380);

        javax.swing.GroupLayout pnlLessonsLayout = new javax.swing.GroupLayout(pnlLessons);
        pnlLessons.setLayout(pnlLessonsLayout);
        pnlLessonsLayout.setHorizontalGroup(
            pnlLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlLessonsLayout.setVerticalGroup(
            pnlLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(pnlLessons);
        pnlLessons.setBounds(0, 0, 530, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        new GameMenuScreen().setVisible(true);
        
        LessonsScreen obj=new LessonsScreen();
        obj.setVisible(false);
        this.dispose();
        
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnLesson2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLesson2ActionPerformed
        // Takes user to Lesson 1
        new Lesson1().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnLesson2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLesson2;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLesson1Stats;
    private javax.swing.JLabel lblLessonNumber;
    private javax.swing.JLabel lblLessonProgress;
    private javax.swing.JLabel lblLessons;
    private javax.swing.JPanel pnlLessons;
    // End of variables declaration//GEN-END:variables
}
