/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BrgtutPkage;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishaan
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        pnlLogin.setPreferredSize(new Dimension(500, 500));
        setSize(new Dimension(580, 400));
        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        pswfPassword = new javax.swing.JPasswordField();
        btnProcess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNewAcc = new javax.swing.JButton();
        lblBackgrnd = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\title.png")); // NOI18N
        getContentPane().add(lblTitle);
        lblTitle.setBounds(200, 10, 170, 60);

        lblUsername.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\playerName30.png")); // NOI18N
        getContentPane().add(lblUsername);
        lblUsername.setBounds(50, 100, 220, 40);

        lblPassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\Password30.png")); // NOI18N
        getContentPane().add(lblPassword);
        lblPassword.setBounds(50, 130, 150, 59);

        txfUsername.setText("Enter Player Name Here");
        txfUsername.setToolTipText("Enter Player Name here!");
        getContentPane().add(txfUsername);
        txfUsername.setBounds(260, 110, 210, 25);

        pswfPassword.setText("jPasswordField1");
        pswfPassword.setToolTipText("Enter Password Here\n");
        getContentPane().add(pswfPassword);
        pswfPassword.setBounds(260, 150, 210, 25);

        btnProcess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProcess.setText("LOGIN");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcess);
        btnProcess.setBounds(240, 200, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\TextFont\\newPlayer30.png")); // NOI18N
        jLabel1.setText("If you are a new Player:Sign Up Below");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 270, 340, 65);

        btnNewAcc.setText("Make New Account");
        btnNewAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewAcc);
        btnNewAcc.setBounds(210, 320, 140, 27);

        lblBackgrnd.setIcon(new javax.swing.ImageIcon("C:\\Users\\ishaan\\Desktop\\University 2019\\CS3\\Sem2\\Capstone\\Phase3\\Images\\background.jpg")); // NOI18N
        lblBackgrnd.setText("jLabel2");
        getContentPane().add(lblBackgrnd);
        lblBackgrnd.setBounds(0, 0, 580, 400);

        pnlLogin.setLayout(null);
        getContentPane().add(pnlLogin);
        pnlLogin.setBounds(70, 380, 110, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Variables
    String userName;
    String password;
    boolean userExists=false;
    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // Login button
        userName=txfUsername.getText();
        password=pswfPassword.getText();
        
        if (userName.equals("")||password.equals("")) {
            JOptionPane.showMessageDialog(null, "Cannot leave username or password field blank"); 
        }
        else{
            user obj=new user(userName, password);
            userExists=obj.authenticateUser();
        //have to read from textfile to look for users info
        //Have to update this
            if (userExists==true) {

               new GameMenuScreen().setVisible(true);

                this.setVisible(false);
                this.dispose(); 
            }
            else{
                JOptionPane.showMessageDialog(null, "User not found!\nEnsure correct username and password entered.\nOR\nNew user must make an account first.");
            }
        }
        
        
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnNewAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccActionPerformed
        // Takes user to new account screen
        new NewAccountScreen().setVisible(true);
        
            this.setVisible(false);
            this.dispose(); 
    }//GEN-LAST:event_btnNewAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewAcc;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackgrnd;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pswfPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
