/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishaan
 */
public class gameMenu extends javax.swing.JFrame {

    /**
     * Creates new form gameMenu
     */
    public gameMenu() {
        initComponents();
        initComponents();
        pnlGameMenu.setPreferredSize(new Dimension(500, 500));
        setSize(new Dimension(540, 360));
        
        btnLessons.setBackground(Color.BLACK);
        btnLessons.setOpaque(true);
        
        btnFreePlay.setBackground(Color.BLACK);
        btnFreePlay.setOpaque(true);
        
        btnExit.setBackground(Color.BLACK);
        btnExit.setOpaque(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGameMenu = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnLessons = new javax.swing.JButton();
        btnFreePlay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblBckGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlGameMenu.setLayout(null);

        lblHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/gameMenuMed.png"))); // NOI18N
        pnlGameMenu.add(lblHeading);
        lblHeading.setBounds(140, 0, 300, 57);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/arrow-112-32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlGameMenu.add(btnBack);
        btnBack.setBounds(0, 0, 60, 50);

        btnLessons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/Lessons30.png"))); // NOI18N
        btnLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessonsActionPerformed(evt);
            }
        });
        pnlGameMenu.add(btnLessons);
        btnLessons.setBounds(170, 110, 180, 50);

        btnFreePlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/freePlay30.png"))); // NOI18N
        btnFreePlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreePlayActionPerformed(evt);
            }
        });
        pnlGameMenu.add(btnFreePlay);
        btnFreePlay.setBounds(170, 170, 180, 50);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/ExitGame30.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlGameMenu.add(btnExit);
        btnExit.setBounds(170, 230, 180, 50);

        lblBckGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/background.jpg"))); // NOI18N
        lblBckGround.setText("jLabel1");
        pnlGameMenu.add(lblBckGround);
        lblBckGround.setBounds(0, 0, 540, 360);

        getContentPane().add(pnlGameMenu);
        pnlGameMenu.setBounds(0, 0, 540, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new exitScreen().setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new LoginScreen().setVisible(true);
        
        gameMenu objGameMenu1=new gameMenu();
        objGameMenu1.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLessonsActionPerformed
        // TODO add your handling code here:
        new lessonsScreen().setVisible(true);
        gameMenu objGameMenu2=new gameMenu();
        objGameMenu2.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnLessonsActionPerformed

    private void btnFreePlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFreePlayActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Coming soon!");
    }//GEN-LAST:event_btnFreePlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFreePlay;
    private javax.swing.JButton btnLessons;
    private javax.swing.JLabel lblBckGround;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JPanel pnlGameMenu;
    // End of variables declaration//GEN-END:variables
}
