/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameboard;

/**
 *
 * @author kevin
 */
public class board extends javax.swing.JFrame {

    /**
     * Creates new form board
     */
    
    public board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 107, 16));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setPreferredSize(new java.awt.Dimension(6000, 4500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(41, 135, 60));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(6000, 4500));
        jPanel1.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/JC.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(720, 270, 190, 280);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/QH.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(660, 270, 180, 280);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/2C.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(600, 270, 180, 280);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/8S.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(550, 280, 180, 260);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/10D.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(480, 270, 180, 270);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/6S.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 270, 180, 270);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/QH.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 260, 190, 280);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/QS.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 260, 180, 290);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/KD.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 270, 180, 260);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/2D.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 250, 180, 310);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/5H.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 260, 180, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/3H.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 270, 173, 264);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cards/ui/assets/10C.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 271, 173, 264);

        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("South");
        jLabel14.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 230, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 990, 4500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board().setVisible(true);
            }
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
