/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.lessons;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishaan
 */
public class lessonsScreen extends javax.swing.JFrame {

    /**
     * Creates new form lessonsScreen
     */
    public lessonsScreen() {
        initComponents();
        pnlLessons.setPreferredSize(new Dimension(500, 500));
        setSize(new Dimension(600, 380));
        
        JOptionPane.showMessageDialog(null, "A scroll pane has been added ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlLessons = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblLessonNum = new javax.swing.JLabel();
        lblLessonProgress = new javax.swing.JLabel();
        btnLesson1 = new javax.swing.JButton();
        btnLesson2 = new javax.swing.JButton();
        lblBckGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlLessons.setLayout(null);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/arrow-112-32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLessons.add(btnBack);
        btnBack.setBounds(0, 0, 60, 50);

        lblHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/LessonsMed.png"))); // NOI18N
        pnlLessons.add(lblHeading);
        lblHeading.setBounds(210, 10, 250, 57);

        lblLessonNum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/lessonNum37.png"))); // NOI18N
        pnlLessons.add(lblLessonNum);
        lblLessonNum.setBounds(40, 70, 250, 67);

        lblLessonProgress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/progress37.png"))); // NOI18N
        pnlLessons.add(lblLessonProgress);
        lblLessonProgress.setBounds(340, 70, 190, 72);

        btnLesson1.setText("LESSON 1");
        btnLesson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLesson1ActionPerformed(evt);
            }
        });
        pnlLessons.add(btnLesson1);
        btnLesson1.setBounds(60, 160, 200, 30);

        btnLesson2.setText("LESSON 2");
        pnlLessons.add(btnLesson2);
        btnLesson2.setBounds(60, 210, 200, 30);

        lblBckGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/background.jpg"))); // NOI18N
        lblBckGround.setText("sdasdsadasdsa");
        pnlLessons.add(lblBckGround);
        lblBckGround.setBounds(0, 0, 600, 380);

        jScrollPane1.setViewportView(pnlLessons);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 600, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new gameMenu().setVisible(true);
        
        lessonsScreen obj=new lessonsScreen();
        obj.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLesson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLesson1ActionPerformed
        // TODO add your handling code here:
        new lesson1Info().setVisible(true);

                this.setVisible(false);
                this.dispose(); 
    }//GEN-LAST:event_btnLesson1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lessonsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lessonsScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLesson1;
    private javax.swing.JButton btnLesson2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBckGround;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLessonNum;
    private javax.swing.JLabel lblLessonProgress;
    private javax.swing.JPanel pnlLessons;
    // End of variables declaration//GEN-END:variables
}
