/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameboard;
import cards.lib.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.JPanel;
import mechanics.lib.*;
/**
 *
 * @author kevin
 */
public class Board1 extends javax.swing.JFrame {

    /**
     * Creates new form board
     */
    private static ArrayList<Card> played_cards;
    private static Memorization memory;
    private static javax.swing.JPanel pane;
    
    public Board1() {
        //initComponents();
        initCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        card1 = new cards.lib.Card();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 107, 16));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setPreferredSize(new java.awt.Dimension(6000, 4500));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(47, 144, 27));
        panel1.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/assests/icon.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InfoBox(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoBoxClose(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HidePane(evt);
            }
        });
        panel1.add(jButton2);
        jButton2.setBounds(410, 320, 145, 80);
        panel1.add(card1);
        card1.setBounds(80, -220, 691, 1056);

        jPanel1.setOpaque(false);
        panel1.add(jPanel1);
        jPanel1.setBounds(780, 260, 80, 220);

        getContentPane().add(panel1);
        panel1.setBounds(-50, 0, 1350, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoBox(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoBox
        JDialog.setDefaultLookAndFeelDecorated(true);
        Object[] selectionValues = { "Spades", "Diamonds", "Clubs", "Hearts" };
        String initialSelection = "Spades";
        Object selection = JOptionPane.showInputDialog(null, "Which played cards would you like to remember?\n(Press enter once finished)" ,
        "Card Memorization", JOptionPane.QUESTION_MESSAGE, null, selectionValues, initialSelection);
        ArrayList<Card> test;
        
        if (selection=="Spades") {
            test=memory.getSpades();
            for (int i=0; i<test.size(); i++) {
            pane.add(test.get(i));
            pane.setVisible(true);
            }
        
        }
        else if (selection=="Diamonds") {
            test=memory.getDiamonds();
            for (int i=0; i<test.size(); i++) {
                pane.add(test.get(i));
                pane.setVisible(true);
            }
        }
        else if (selection=="Hearts") {
            test=memory.getHearts();
            for (int i=0; i<test.size(); i++) {
                pane.add(test.get(i));
                pane.setVisible(true);
            }
        }
        else if (selection=="Clubs") {
            test=memory.getClubs();
            for (int i=0; i<5; i++) {
                pane.add(test.get(i));
                pane.setVisible(true);
            }
        }
        /*
        
        
        for (int i=0; i<test.size(); i++) {
            pane.add(test.get(i));
        }
        pane.setVisible(true);*/
    }//GEN-LAST:event_InfoBox

    private void InfoBoxClose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoBoxClose
        //pane.setVisible(false);
    }//GEN-LAST:event_InfoBoxClose

    private void HidePane(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HidePane
        pane.removeAll();
        pane.setVisible(false);
    }//GEN-LAST:event_HidePane

    private void initCustom() {
        
        jButton2 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        
        Deck deck = new Deck();
        deck.shuffle(new Random());
        
        played_cards = new ArrayList();
        memory = new Memorization(played_cards);
        
        while (!deck.isEmpty()) {
            played_cards.add(deck.removeTop());
        }
        
        
        pane = new javax.swing.JPanel();
    
        pane.setBounds(150, 300, 1050, 132);
      
        System.out.println(memory.getPlayedSize());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 107, 16));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setPreferredSize(new java.awt.Dimension(6000, 4500));
        getContentPane().setLayout(null);

        
        panel1.setBackground(new java.awt.Color(47, 144, 27));
        panel1.setLayout(null);
        
        Card card = new Card(2,1);
        Card card1 = new Card(2,2);
        pane.setLayout(new javax.swing.BoxLayout(pane, javax.swing.BoxLayout.LINE_AXIS));
        pane.setOpaque(false);
        //pane.add(card);
        //pane.add(card1);
        /*for (int i=0; i<13; i++) {
            pane.add(played_cards.get(i));
        }*/
        
        
        jButton2.setIcon(new javax.swing.ImageIcon("/home/kevin/Desktop/Memorization/icon.png")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoBox(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoBoxClose(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HidePane(evt);
            }
        });
        
        
        
        
        /* ArrayList<Card> test = new ArrayList();
        test = memory.getClubs();
        
        for (int i=0; i<test.size(); i++) {
            pane.add(test.get(i));
        } */
        
        panel1.add(pane);
        panel1.add(jButton2);
        jButton2.setBounds(1250, 0, 75, 75);
        //card.setBounds(80, 220, 87, 132);
        
        
        getContentPane().add(panel1);
        panel1.setBounds(-50, 0, 1350, 760);
        pane.setBackground(Color.black);
        
        pane.setVisible(false);
        pack();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Board1 game = new Board1();
        //game.initCustom();
        
        
        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board1().setVisible(true);
                //pane.add(played_cards.get(0));
                panel1.add(new Card(2,1));
            }

        }); */
        //game.pack();
        game.setVisible(true);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cards.lib.Card card1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private static java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
