/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;


import java.awt.Dimension;

/**
 *
 * @author Ishaan
 */
public class Lesson1_Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Lesson1_Quiz
     */
    public Lesson1_Quiz() {
        initComponents();
        pnlMain.setPreferredSize(new Dimension(500, 500));
        setSize(new Dimension(1060,620)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cmbQ6 = new javax.swing.JComboBox();
        cmbQ1 = new javax.swing.JComboBox();
        cmbQ2 = new javax.swing.JComboBox();
        cmbQ3 = new javax.swing.JComboBox();
        cmbQ4 = new javax.swing.JComboBox();
        cmbQ5 = new javax.swing.JComboBox();
        cmbQ8 = new javax.swing.JComboBox();
        cmbQ7 = new javax.swing.JComboBox();
        btnProcess = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlMain.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/lesson1_40.png"))); // NOI18N
        pnlMain.add(jLabel1);
        jLabel1.setBounds(370, 0, 194, 73);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/arrow-112-32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlMain.add(btnBack);
        btnBack.setBounds(0, 0, 60, 50);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbQ6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c", "d" }));
        jPanel1.add(cmbQ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 667, -1, -1));

        cmbQ1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c", "d" }));
        jPanel1.add(cmbQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 11, -1, -1));

        cmbQ2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c", "d" }));
        jPanel1.add(cmbQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 158, -1, -1));

        cmbQ3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c" }));
        jPanel1.add(cmbQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 306, -1, -1));

        cmbQ4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c" }));
        jPanel1.add(cmbQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 431, -1, -1));

        cmbQ5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c" }));
        jPanel1.add(cmbQ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 545, -1, -1));

        cmbQ8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c", "d" }));
        jPanel1.add(cmbQ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 932, -1, -1));

        cmbQ7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Answer", "a", "b", "c", "d" }));
        jPanel1.add(cmbQ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 800, -1, -1));

        btnProcess.setText("PROCESS");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1050, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/q1-20.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/q2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/q3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 306, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/q4.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 431, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/remainingQ.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/a4Page2.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 790));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/a4Page2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 740, 790));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/a4Page2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 740, 460));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/a4Page2.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, 460, 460));

        jScrollPane1.setViewportView(jPanel1);

        pnlMain.add(jScrollPane1);
        jScrollPane1.setBounds(49, 120, 960, 430);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/quiz.png"))); // NOI18N
        pnlMain.add(jLabel3);
        jLabel3.setBounds(280, 60, 410, 50);

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAssets/greenBackground.jpg"))); // NOI18N
        lblBackGround.setText("jLabel12");
        pnlMain.add(lblBackGround);
        lblBackGround.setBounds(0, 0, 1060, 640);

        getContentPane().add(pnlMain);
        pnlMain.setBounds(0, 0, 1060, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Variables
    
    String lessonNum="Lesson 1"; //Current lesson number
    int totalQ=8;
    Integer arrUsersAnswers[]=new Integer[8];
    
    ArrayList<String> arrLUserAns=new ArrayList<>();
    ArrayList<String> arrLModelAns=new ArrayList<>();
    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // Process the selected answers
           int arrModelAnswers[]={4,3,1,3,3,4,3,3};//I have to change question 6 answers
        
        
        arrUsersAnswers[0]=cmbQ1.getSelectedIndex();
        arrUsersAnswers[1]=cmbQ2.getSelectedIndex();
        arrUsersAnswers[2]=cmbQ3.getSelectedIndex();
        arrUsersAnswers[3]=cmbQ4.getSelectedIndex();
        arrUsersAnswers[4]=cmbQ5.getSelectedIndex();
        arrUsersAnswers[5]=cmbQ6.getSelectedIndex();
        arrUsersAnswers[6]=cmbQ7.getSelectedIndex();
        arrUsersAnswers[7]=cmbQ8.getSelectedIndex();
        
        //Using arrays to ensure that the answer matches the question
        for (int i = 0; i < 8; i++) {
            arrLModelAns.add(arrModelAnswers[i]+"");
            arrLUserAns.add(arrUsersAnswers[i]+"");
            
        }
        Lesson obj=new Lesson(lessonNum, arrLModelAns, arrLUserAns);
        
        if (obj.evalAnswers()==true) {
            JOptionPane.showMessageDialog(null, "You have successfully completed Lesson 1!\nYou have achieved 8/8");
            new gameMenu().setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "You have not successfully completed Lesson 1.\nYou achieved "+obj.numIncorrectAns()+"/8");
            JOptionPane.showMessageDialog(null, "Here are the questions you got incorrect:\n"+obj.getIncorrectAnswers());
            new gameMenu().setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Back to lessons screen
        new lessonsScreen().setVisible(true);

                this.setVisible(false);
                this.dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lesson1_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lesson1_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lesson1_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lesson1_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lesson1_Quiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox cmbQ1;
    private javax.swing.JComboBox cmbQ2;
    private javax.swing.JComboBox cmbQ3;
    private javax.swing.JComboBox cmbQ4;
    private javax.swing.JComboBox cmbQ5;
    private javax.swing.JComboBox cmbQ6;
    private javax.swing.JComboBox cmbQ7;
    private javax.swing.JComboBox cmbQ8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
